### ISSUE TITLE
Desire lines

### ISSUE THREAD

**Issue by HatemKallel** [AequilibraE/qaequilibrae#133]
Hello, how does the Desire line tool work ? Everytime I load my matrice I get a DelaunayLines table with strange values (different from those I have in my matrice). 

Thank you very much. 

Hatem

**Comment by pedrocamargo** [comment]
@HatemKallel ,  Github issues are not the best forum to ask questions (unless you have something you think is really working poorly).  Please send your questions to aequilibrae@googlegroups.com

In the meantime, Delaunay Lines are one thing, and desire lines are a different thing (you can choose what to create).  If you want to understand what Delaunay Lines are, the original blog post on it might be a good place to start https://www.xl-optim.com/delaunay/ (full paper available if you'd like)
