### ISSUE TITLE
GUI on the network preparation is not working

### ISSUE THREAD

**Issue by natachai** [AequilibraE/qaequilibrae#146]
I am using QGIS 3.8.3-Zanzibar. The plugin for AequilibraE is successful installed, as well as the extra package required by the program.
I can open the window from the network preparation menu but I can not select the network layer from the GUI window nothing working.

From the attached picture, I am testing by adding road network layer but nothing show up for for me to select on the network layer slot.

![111](https://user-images.githubusercontent.com/8148215/66258300-d33fda80-e7cd-11e9-8ba0-357383a4dc48.png)

**Comment by pedrocamargo** [comment]
Please check if your layer is a LineString layer or MultiLineString one.  Transportation networks are not defined for MultiLineString layers.  If you have a LineString layer, please attach it here so I can take a look

**Comment by natachai** [comment]
Thank you for your best help pedrocamargo

I got back to my old computer and working on AequilibraE with QGIS 2.x. This network was working just fine. However, please find the attache file for the network. I would really love to use the AequilibraE on my new notebook though.


[road.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/3693890/road.zip)

**Comment by pedrocamargo** [comment]
@natachai, as I thought, you have a MultiLineString layer, not a LineString one (I did ask you to check, didn't I?)

This was a well-documented issue in the previous version that was fixed.

https://github.com/AequilibraE/AequilibraE-GUI/issues/112

**Comment by pedrocamargo** [comment]
![2019-10-06 08_59_31-Window](https://user-images.githubusercontent.com/7377666/66266123-a2d15e00-e818-11e9-9220-cbe000d6e43d.png)

**Comment by pedrocamargo** [comment]
@natachai You seem to be working with OSM.  Take a look here: http://www.aequilibrae.com/qgis/networksfromscratch.html
