### ISSUE TITLE
Manual selection of links is no longer possible

### ISSUE THREAD

**Issue by YuryZammit** [AequilibraE/qaequilibrae#155]
In previous versions of AeQ, particularly in QGIS 2.18, it was possible to create network graphs of link layers which had queries on them.  In this way, the network could be adjusted as needed on a large scale.  I do not think this is possible in the latest version, because if I do a query to exclude certain links during a traffic assignment exercise, these are still used.

**Comment by pedrocamargo** [comment]
This is really an issue we will have to address with the underlying API (the aequilibrae Python library)

**Comment by pedrocamargo** [comment]
@YuryZammit , I might be able to address this issue this week and include that in the next release. Can you take this issue to the AequilibraE Python library as well? https://github.com/AequilibraE/aequilibrae/issues

**Comment by pedrocamargo** [comment]
@YuryZammit , I have already added that feature to the AequilibraE API, so now I have to add it to the GUI, so the feature should be coming soon

**Comment by pedrocamargo** [comment]
It will also be available in the next release

**Comment by YuryZammit** [comment]
Excellent! Thanks.
