### ISSUE TITLE
Aequilibrae panel cannot be 'narrowed' when there is a long project file path

### ISSUE THREAD

**Issue by YuryZammit** [AequilibraE/qaequilibrae#156]

**Comment by pedrocamargo** [comment]
The solution was to add a checkbox that cleans the tab widget when you don't want to show it.  Removing the tab widget altogether seems to be impossible, as **QTabWidget.setVisible(False)** has no effect and that the toolbar has no method **removeWidget()**

**Comment by pedrocamargo** [comment]
@YuryZammit , the new version has already been uploaded to the repository and should be approved soon.

**Comment by pedrocamargo** [comment]
Version 0.6.3 (experimental) includes the fix for this bug. It has already been uploaded to the QGIS repository and is waiting for approval.

**Comment by YuryZammit** [comment]
That is great! Thanks.
