### ISSUE TITLE
Visualizing Matrix Data with Polygon Layers

### ISSUE THREAD

**Issue by danielsclint** [AequilibraE/qaequilibrae#160]
Hi Pedro-

I want to use your code base to help with visualizing travel skim matrices (e.g., time, cost, distance). I was able to get the OMX table viewer to work with a little finessing of the QGis libraries. That all works great now.

The next step is to link the matrix to the map. For example, I would really like to be able to highlight a row or column in the matrix and the map to update like the image below.

![image](https://user-images.githubusercontent.com/4667111/80533994-5df74b00-8953-11ea-8c97-d215230d0c32.png)

I spent some time modifying [`display_aequilibrae_formats_dialog.py`](https://github.com/AequilibraE/AequilibraE-GUI/blob/master/matrix_procedures/display_aequilibrae_formats_dialog.py), and I got the general look and feel of what I wanted. Before I do too much further with this, is this something that you view as compatible with your library?

![image](https://user-images.githubusercontent.com/4667111/80535135-2be6e880-8955-11ea-8702-d75a87bc5e01.png)

I added a row of controls to the bottom of the matrix mapper to specify whether to map the selected rows and which Polygon layer and field to match the row of data too.

![image](https://user-images.githubusercontent.com/4667111/80536793-c516fe80-8957-11ea-9b2e-32c25fcfd710.png)

This is still a work in progress, but I wanted to coordinate with you first, before I invest too heavily in integrating to your tool.

Thanks.

Clint

**Comment by pedrocamargo** [comment]
That is absolutely brilliant, @danielsclint , and I would very much appreciate a pull request with that !!!

Have you considered the case of highlighting a column as well?

**Comment by danielsclint** [comment]
Okay, give me a week or so to work through it. I need to determine the most efficient way to handle the virtual layer in the map window. I've got a few hours over the next week to focus on this. Its a mixture of general interest and professional need. Once I get a solid working prototype, I'll issue a pull request to continue the discussion on refinements. 

Admittedly, I don't know the AequilibraE API as well as you, so I'm sure there may be some more efficient ways to gather and display data under the hood, once you see my approach.

(And, yes, I'm working on it to map based on the highlighted row (from zone to all other zones) or column (to zone from all other zones).)

Thanks.

**Comment by pedrocamargo** [comment]
Hey Clint, Just FYI, I made a small change to the classes you were working on, where I add the path to the file being visualized to the upper bar of the GUI. So if you see a conflict when you issue your pull request, don't worry.

**Comment by pedrocamargo** [comment]
Have you ever advanced this, @danielsclint ?
