### ISSUE TITLE
Add centroid connectors not connecting to network

### ISSUE THREAD

**Issue by grabijas** [AequilibraE/qaequilibrae#167]
Used the "Add centroid connectors" program to connect the centroid nodes to an existing network.  Program created a new link for each centroid but this left a gap with the closest node in the existing network.  See node #4 (or any node 15 or less) for example.  In the case of node #4 a new link id 299632 was added from centroid node 4 to new node 341130.  This left a gap to the nearest existing node in the network (339265) - zoom to see it.  This prevented a path from being calculated between node #4 and the rest of the centroids.  I corrected this by moving the existing node 339265 on top of 341130 which created the network connection.

This issue misconnected paths between all of the 15 centroids.  I included the CO_impedance file that shows high values between all centroids.

Hope this helps.

Gregg
[CO_network_centroids.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/4588996/CO_network_centroids.zip)
[CO_impedance.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/4589000/CO_impedance.zip)

**Comment by pedrocamargo** [comment]
Same issue as #164
