### ISSUE TITLE
QGIS freezes when starting a new project from OSM

### ISSUE THREAD

**Issue by andreaCola** [AequilibraE/qaequilibrae#169]
I was trying to initialise a project by downloading OSM from canvas.
I left it downloading for more than 2 hours, but couldn't see any progress and eventually QGIS crashed.
Also tried on another machine with same result.

I'm using QGIS 3.12 on a windows machine.
Didn't do any spatialite installation when I tried.

**Comment by pedrocamargo** [comment]
Will be fixed in the next version, as the OSM import code has received dramatic changes since this version.

**Comment by Art-Ev** [comment]
I think we can close this issue, OSM import function now gives a lot of feedback on current progress
