### ISSUE TITLE
Two classes traffic assignment | same (repeated) resulting flows

### ISSUE THREAD

**Issue by gmormilho** [AequilibraE/qaequilibrae#170]
I am with the following problem: I do a traffic assignment with two classes, however, both resulting flows are the same. That is, both files with the resulting flows have the same values. The matrices are different for each class.

Does anyone else has the same problem?

I am using QGIS 3.10.7 A Coruña and AequilibriaE 0.6.2.

**Comment by pedrocamargo** [comment]
Can you make your assignment specifications known so I can try to reproduce it (time & capacity fields, BPR parameters, PCEs)?  I am assuming these are the same model files you sent to the mailing group...

**Comment by gmormilho** [comment]
Yes, the same as the mailing group.

[Aloc_flows.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/5405354/Aloc_flows.zip)

I am using QGIS 3.10.7 A Coruña and AequilibriaE 0.6.2.

I send my files attached, if anyone wants to reproduce de results. The input settings are:
**TRAFFIC CLASSES**
Matrix name    carro
Mode    car (c)
PCE    1.0000

Matrix name moto
Mode moto (m)
PCE 0.5000

**ASSIGNMENT**
**Algorithm**
Algorithm: bfw (default)
Relative gap: 0.0001 (default)
Maximum iterations: 250 (default)
Block flow through centroids: yes (default)
**Network information**
Capacity: CapNum
Free Flow Travel time: FreeFlowTime
**Volume-delay function**
Function: bpr (default)
alpha: Alpha
beta: Beta

Regards

**Comment by pedrocamargo** [comment]
I have implemented this assignment in Python and it is apparently working as it should, but I found data issues.

--> Capacity & FreeFlowTime has **Null** values for centroid connectors

And are you sure of your Alpha & Beta values? The default values for alpha and beta are 0.15 and 4.0, respectively, and while I am not going to get into the details of the BPR, I would bet that 2.0 and 2.0 (the values in the database) are wrong.

The assignment Values I got are below, and so is the log file for the assignment
[aequilibrae.log](https://github.com/AequilibraE/AequilibraE-GUI/files/5405433/aequilibrae.log)

[mormilho.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/5405432/mormilho.zip)

**Comment by gmormilho** [comment]
I will try with python!

@pedrocamargo , I just checked my database and I did not find any connectors with null values for Capacity or FreeFlowTime. Could you tell me the IDs of the links you found?

About Alpha and Beta, I am still ~~fighting with~~ calibrating them.

**Comment by gmormilho** [comment]
Pedro,

I just reproduced the assignment with python, and I get the exact same results, with the repeated values for both modes.

I attach my JupiterNotebook file here.

[Aloc_Sarandi_python.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/5433685/Aloc_Sarandi_python.zip)

Regards.

**Comment by pedrocamargo** [comment]
You used the same matrix twice, @gmormilho.

The appropriate way of dealing with the matrices is this:

![2020-10-25 07_16_14-Window](https://user-images.githubusercontent.com/7377666/97093789-56aac300-1692-11eb-9015-ac2386f38c77.png)


Notebook attached.

[mormilho.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/5433790/mormilho.zip)

**Comment by Art-Ev** [comment]
Have take a look at the problem (GUI side).
Research problem procedure : 
- 3 matrices : 
    - moto -> full of 1
    - car -> full of 10
    - freight -> full of 100
  
Assign with GUI using one .aem file (using multiple files cause an error when trying to assign)
[Mode_matrix.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/6671658/Mode_matrix.zip)

### First try :

Assign them through 3 user classes and 1 traffic class
-> Success !
Resulting flows :
![image](https://user-images.githubusercontent.com/83211842/122434780-afb7c600-cf97-11eb-97a2-752db4b10187.png)

Problem : this is limitate to only one network mode... and you need to take care of PVE coefficient in your matrices

### Second try :
Using two or the three matrices traffic classes (one matrix per class) : traffic flows are the same for each classes (ooh ooooh... 😢 )
When assign only cars and motos : 
![image](https://user-images.githubusercontent.com/83211842/122436118-d9bdb800-cf98-11eb-911b-1a8648ef405f.png)

Could be a result export problem but columns name are good so...
I don't know if it's the bigger or the last configured matrix but it seems to use the same matrix for all traffic classes (for last example moto traffics, if I use the 3 modes it's freight)

### Search for problem origin :
Have take a look at the plugin code with a focus on traffic_assignment_dialog.py (GUI only file) but unfortunately did not manage to understand everything...

Maybe something with an incorrect matrix attribution when creating traffic classes (line 249 ?)
https://github.com/AequilibraE/AequilibraE-GUI/blob/master/paths_procedures/traffic_assignment_dialog.py

Can you take a quick look and confirm this @pedrocamargo or @jamiecook ? 
This prevents the use of multiple traffic classes with GUI which is quite annoying... maybe some hot fix is possible allowing usage of GUI before the next update  ? 😇

**Comment by pedrocamargo** [comment]
Hey Arthur,
                       I think the next update will come rather quickly, as I will probably be a little less busy in a month or so...  That's all I can offer at the moment!

**Comment by pedrocamargo** [comment]
The issue in the Python package has been eliminated.
