### ISSUE TITLE
Symbology of stacked bandwidths change

### ISSUE THREAD

**Issue by james-ramsey** [AequilibraE/qaequilibrae#173]
Consider changing the default symbology for stacked bandwidths to have join style = Miter, and Cap style = Flat. I find these look much better for this type of plot as bandwidths don't overlap at node vertices.

**Comment by pedrocamargo** [comment]
@james-ramsey, you will have to reach some sort of agreement with Harry Smithers there.  At least inside VLC you should be able to reach a consensus.
https://github.com/AequilibraE/AequilibraE-GUI/issues/64
May I suggest you talk to @jamiecook and see how you guys can figure this one out and issue a PR?
