### ISSUE TITLE
Help with preparing a network

### ISSUE THREAD

**Issue by mauporte** [AequilibraE/qaequilibrae#174]
I am trying to learn AequilibraE but I can't even get started: 
 - I create 2 new shapefiles: one for lines and the other for points as shown in the image.
![1](https://user-images.githubusercontent.com/83365572/116446501-a07c8d80-a81c-11eb-88bb-f31691eaebf6.png)
- ID's are all single digit integers, and yet nothing happens when I try to create the network, as shown in the image:
![2](https://user-images.githubusercontent.com/83365572/116446554-ad997c80-a81c-11eb-9496-cdffd68d3924.png)
-Ok, maybe it would work if i told it to create its own node layer, nope:
![3](https://user-images.githubusercontent.com/83365572/116446649-c73ac400-a81c-11eb-8e10-6a70ee047df7.png)

I already tried restarting the whole process (delete shapefiles, create new ones and redraw the features) 5 different times in different directories.

**Comment by pedrocamargo** [comment]
@mauporte , this is not the appropriate place for asking questions. Please send your questions to the mailing list (easy to find by googling it)
