### ISSUE TITLE
Add xml/json file to store/load assignment menu parameters

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/qaequilibrae#177]
Enhancement idea :
Create an XML/json file to export/import assignment dialog menu parameters.
This could allow using preconfigured parameters for assignment dialogmenu and save lot of time (and guarantee consistency).

Maybe could be also used to later create a script in processing provider for assignments.

**Comment by pedrocamargo** [comment]
Hey @Art-Ev , this fits better in the Python library, as the menus themselves are just a replication of what goes into the GUI

**Comment by Art-Ev** [comment]
For a first implementation, It might be possible to proceed as for :
[https://github.com/Arpapiemonte/openoise-map/blob/master/tools/do_CalculateNoiseLevels.py](url)

Or maybe the part for trafic classes to assign is not compatible with this method ?

**Comment by pedrocamargo** [comment]
This example is VERY good...  We might have do that before implementing the Python stuff...

**Comment by Art-Ev** [comment]
New idea : just implement a json export uring asisgnment and, then, run assignment using QGIS processing provider with a function just like #250 (would take the json as only input).

**Comment by pedrocamargo** [comment]
> New idea : just implement a json export uring asisgnment and, then, run assignment using QGIS processing provider with a function just like #250 (would take the json as only input).

@r-akemii , can you add this as another issue as feature request?
