### ISSUE TITLE
Binary Error when creating Project from Layers (QGIS)

### ISSUE THREAD

**Issue by mertcubukcu** [AequilibraE/qaequilibrae#179]
Hi,
I am using QGIS v.3.16.13 and AequilibraE package.
I keep getting "Binary Error: : Please download it from the repository using the downloader from the menu."
I have downloaded the zip file from 
https://www.aequilibrae.com/binaries/v.0.6.1/binaries.zip 
and unzipped the files to the folder below as suggested by the package:
C:\Users\mertc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae\aequilibrae
but I keep getting the error message.
Am I missing something?
Regards,
mert

**Comment by pedrocamargo** [comment]
Mert,
            The issue reporting templates have CLEAR instructions that you should ask your questions on the user forum before reporting a bug.

My guess is that you are probably using a version of QGIS that has Python 3.9, which is not yet supported by AequilibraE for QGIS (upcoming 0.7.x version). Since this is a question and not a proper bug report, I am closing it for now.

https://groups.google.com/g/aequilibrae
