### ISSUE TITLE
Unable to create project with "Create Project from layers" function

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/qaequilibrae#181]
**Describe the bug**

Error when creating project from layer:
\AequilibraE\project_procedures\creates_transponet_dialog.py", line 310, in run_thread
              self.worker_thread.ProgressValue.connect(self.progress_value_from_thread)
             AttributeError: 'CreatesTranspoNetProcedure' object has no attribute 'ProgressValue'

**To Reproduce**

Creating project from layer.
For example from this network (also tested on another network with the same result) : 
[NetworkExample.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/8461936/NetworkExample.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QGIS Version 3.22 (with new AequilibraE GUI plugin 😄)

**Comment by Art-Ev** [comment]
Same error with matrix import from OpenLayers:
\AequilibraE\matrix_procedures\load_matrix_dialog.py", line 149, in run_thread
    self.worker_thread.ProgressValue.connect(self.progress_value_from_thread)
AttributeError: 'LoadMatrix' object has no attribute 'ProgressValue'

(Using this project : [St_Varent.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/8462345/St_Varent.zip) )

**Comment by pedrocamargo** [comment]
I would not expect to have many of these, as I am surprised there are any!!

 I replaced the worker thread class throughout the software, but have clearly failed to do the stitching (and testing) properly. Wil fix it soon.

**Comment by pedrocamargo** [comment]
A new version fixing this issue has been uploaded

**Comment by Art-Ev** [comment]
Bearer of bad news is back @pedrocamargo :

- Matrix import (from openlayer) when trying to save matrix :
	  <details>

	  AttributeError: 'MatrixReblocking' object has no attribute 'ProgressValue' 
	  Traceback (most recent call last):
	    File "%profile%/python/plugins\AequilibraE\matrix_procedures\load_matrix_dialog.py", line 317, in get_name_and_save_to_disk
	      self.prepare_final_matrix()
	    File "%profile%/python/plugins\AequilibraE\matrix_procedures\load_matrix_dialog.py", line 331, in prepare_final_matrix
	      self.run_thread()
	    File "%profile%/python/plugins\AequilibraE\matrix_procedures\load_matrix_dialog.py", line 149, in run_thread
	      self.worker_thread.ProgressValue.connect(self.progress_value_from_thread)
	  AttributeError: 'MatrixReblocking' object has no attribute 'ProgressValue'
	  
	</details>

- Creating project from layers with NetworkExample (first post in this thread) : seems to stop unexpectedly before the end and without error 
	  <details>

			- No error message
			- No cpu or disk usage
			- Dialog at 0% displaying "Transferring links"
			- Project folder is containing : 
					1. "matrices" folder
					2. aequilibrae.log (2022-04-22 17:41:34,340;aequilibrae;INFO ; Created project on D:/AequilibraE/Projets/Test\new_project)
					3. Parameters.yml
					4. Project database.sqlite (file size: 6 220ko, no link in sqlite file)

	</details>

- Creating project from layers with old aequilibrae project (working with previous AequilibraE-GUI version, just importing nodes and links layer in QGIS from .sqlite and then select them as layers) : had to relaunch qgis to be able to open new project but nodes import seems buggy
	<details>

			- No error message
			- old centroids have not been loaded but new nodes have been created instead (new node_id and is_centroid set at 0)
			- all node_id have been changed during import
			- Using same initial layers but stored in a .gpkg file is resulting in unexpected end just like NetworkExample but menu dialog is displaying "Transferring nodes" (project_database.sqlite still at only 6 220ko containing only one link on 19 214 and 2 nodes on 18 523, id's for nodes and link do not correspond to their initial id)
			- Cannot provide used network sorry (confidential)
		
	</details>

**Comment by pedrocamargo** [comment]
@Art-Ev , The crashing should be fixed.

The second issue is also crashing (but since it is on a thread, you would need to open the little message bar on the right lower corner
![image](https://user-images.githubusercontent.com/7377666/164951254-9b7a673e-11ee-4db1-8a76-e7adbd2bada1.png)

This is not actually a bug, but a case where the input data has no projection system, and therefore AequilibraE does not know how to convert the data.  I have included a check for that to give the user an error message before the importing process begins.

These two issues have been updated and a new version has been uploaded.

The last issue is a little more complicated, so I am investigating.  This will probably come with a new feature of "upgrading old aequilibrae models", as link_types, modes, list of matrices and other things should also be carried through.

**Comment by Art-Ev** [comment]
- Matrix import/export: perfectly working !
- 2nd issue : good by assigning a SCR (my bad, not seen that the file was badly generated), just some strange importing errors which results in a partial network
- 3rd issue : could be related to changes to [project_procedures/creates_transponet_procedure.py](https://github.com/AequilibraE/AequilibraE-GUI/commit/7d3d9610c4db16aa69c57f35a542966276228b16#diff-229a343def18b588cbf0a4c63ff69c6263ee816d7c27fd62bbdc9f37e3b897b9) (long time ago: last summer) where you replaced self.transfer_layer_features("nodes" by self.renumber_nodes(). I've tried to replaced function with the old one but then I got importing errors for lot of nodes

Will continue to investigate 2nd and 3rd issues

**Comment by pedrocamargo** [comment]
Good insight.  I will take a look at this procedure this weekend.  I have recently developed some similar stuff at Argonne but using a lot more SQL, which I will try to transfer here. It should simplify the code substantially

**Comment by Art-Ev** [comment]
Hi ! Does somebody find something (maybe just a direction) to allow project creation from layers which was working bedore ? (keeping ID's from provided layers) @pedrocamargo, @r-akemii ?

**Comment by r-akemii** [comment]
Hey @Art-Ev, I ran an example with links with _link_id_ that doesn't start in 1, and the project created seems to be working fine, keeping their original ID. Do you have any data that didn't work previously to provide me so I can better investigate this issue?

**Comment by r-akemii** [comment]
@Art-Ev I did some modifications in *Create projects from layers* that might have solved the issue you reported. Could you please check and see if it is working fine now?

**Comment by r-akemii** [comment]
There was indeed a bug in _Create functions from layers_ that was solved in #291.
