### ISSUE TITLE
[New Feature] Load AequilibraE project on qgis project opening

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/qaequilibrae#186]
Now that AequilibraE projects are based on a folder:
QGIS projects can store some python macros (project -> properties -> Macros) to launch for example when opening a qgis project (macro store in qgz file).
We could create a script to load AequilibraE project for the folder in which qgis project is stored (QgsProject.instance().absolutePath())

This way we could store a qgz file in AequilibraE folder and qgis will load AequilibraE project by itself when opening qgz file!

I've tried to create this by inspiring myself with load_project_action.py but cannot achieve it due to the qgis_project parameter that I don't fully understand, can somebody give me a hint ?

**Comment by pedrocamargo** [comment]
Do you want to start a pull request for me to give you a hand on this?

**Comment by Art-Ev** [comment]
If the code is within a qgz project I don't know if a PR is relevant, current file with an aequilibrae project : [St_Varent.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/8671236/St_Varent.zip)
To access code :
- Open StVarent_model.qgz
- Go to qgis project menu (the one in the upper left corner) -> "Properties" -> "Macros"

For now I don't understand how to link to EquilibraEMenu, maybe you have some ideas ?

Another solution could be to integrate a test when AequilibraE is loading (maybe directly in AequilibraEMenu.py ?) and if qgis project is stored in a relevant folder, load the projet. The issue is that QGIS is starting all plugins and, only after, load the project (but perhaps the path of the project is already accessible during plugins initialisation)

**Comment by pedrocamargo** [comment]
I am not sure this is possible, but @r-akemii  will take a look at it

**Comment by pedrocamargo** [comment]
@r-akemii , there are tips on how to do this here: https://github.com/pedrocamargo/getthemfiltered/pull/13
