### ISSUE TITLE
Legacy-install-failure in installing aequilibrae package

### ISSUE THREAD

**Issue by upper-stack** [AequilibraE/qaequilibrae#188]
I'm trying to install the aequlibrae package using the polarislib.whl library but i get an error on cythoning the AoN.pyx file

 cythoning C:\Users\xxx\AppData\Local\Temp\pip-install-0x25yc5r\aequilibrae_105756bf6ea841918a50d98576181abd\aequilibrae/paths\AoN.pyx to C:\Users\xxx\AppData\Local\Temp\pip-install-0x25yc5r\aequilibrae_105756bf6ea841918a50d98576181abd\aequilibrae/paths\AoN.cpp
      error: C:\Users\xxx\AppData\Local\Temp\pip-install-0x25yc5r\aequilibrae_105756bf6ea841918a50d98576181abd\aequilibrae\paths\AoN.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aequilibrae
  Running setup.py clean for aequilibrae
Failed to build aequilibrae
Installing collected packages: aequilibrae, polarislib
  Running setup.py install for aequilibrae ... error
  error: subprocess-exited-with-error

**Comment by pedrocamargo** [comment]
Philip, you have completely ignored the issue creation instructions, so I am closing the issue.  Feel free to open a new issue (if you think that's the case) or follow the instructions for the other steps that must preced the creation of bugs (I am not even sure this is the right repo, as this is for the GUI, not the Python package).

![image](https://user-images.githubusercontent.com/7377666/171122880-9d3b8bc2-0a74-46d2-934f-a9fb9548ca3c.png)
