### ISSUE TITLE
Import from OSM resulting in a single node and links connecting it only this node

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/qaequilibrae#200]
Since parameter file as been moved to AequilibraE projects, how can we specified spatialite folder ?

I suspect that this is the origin of the systematically wrong OSM imports (all nodes replaced by one)
![image](https://user-images.githubusercontent.com/83211842/196174900-26c41cc1-cd29-4123-a65d-f0d6f4d48922.png)

Generated project:
[new_project.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/9800324/new_project.zip)

Also, have somebody have somewhere an example of OSM import/project creation with last versions of AequilibraE ? (documentation is outdated)

**Comment by pedrocamargo** [comment]
Are you looking for QGIS documentation?  The Python example up-to-date on www.aequilibrae.com

Spatialite does not play a role if you are doing inside QGIS, as it uses the spatialite version shipped with QGIS.

I also don't think that the issue with the import is in the parameters.  What is your projection in your project when you started the import? Try to make sure it is WGS84 4326

**Comment by Art-Ev** [comment]
Import was done using the name of the city :P Have redid it changing CRS and same result : 
![image](https://user-images.githubusercontent.com/83211842/196181963-b37dd47f-9c05-4bce-91df-794846721756.png)

Thanks for the precision on spatialite "version"

**Comment by pedrocamargo** [comment]
I could not reproduce the issue  

![image](https://user-images.githubusercontent.com/7377666/196182976-5a24eefb-b604-440f-92fe-bbd09dd54da4.png)

![image](https://user-images.githubusercontent.com/7377666/196183265-1a85aaf0-8b5f-454a-a260-5d929c56fe8d.png)
[new_project.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/9800693/new_project.zip)

**Comment by Art-Ev** [comment]
I'm trying to update QGIS... just in case (was using 3.26.1)

**Comment by Art-Ev** [comment]
Same result after update : QGIS 3.26.3 & 3.22.11 😢 

Interesting thing, using : 
``from aequilibrae.project import Project``
``fldr = 'D:/Test/'``
``project = Project()``
``project.new(fldr)``
``project.network.create_from_osm(place_name="Saint Varent")``
``project.close()``

Perfect result via pycharm (1068 nodes), wrong one using python console directly in QGIS (1 node)
I'll continue to investigate later...

NB: in your procedure report, number of nodes is wrong... don't know why

**Comment by Art-Ev** [comment]
On another computer I have no problem, I certainly broke something playing with my qgis python env 😝  my bad, sorry
