### ISSUE TITLE
QGIS chash when try to create new table in MS SQL!

### ISSUE THREAD

**Issue by snwl** [AequilibraE/qaequilibrae#205]
## User Feedback

MS SQL Server. Right mouse click --> New table --> QGIS crashed.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004148 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by jamiecook** [comment]
Hi @snwl - MS SQL Server is not in any way supported by Aequilibrae so I'm not really sure how to do anything except close this. 

If you are saying that MS SQL Server works normally until you install the Aequilbrae plugin? 
If so we'd need to double check that un-installing it solves the problem and then work toward figuring out how Aequilibrae and SQLServer are interacting.
