### ISSUE TITLE
metadata.txt home page

### ISSUE THREAD

**Issue by luipir** [AequilibraE/qaequilibrae#22]
Hi

the homepage in metadata.txt have to be a correct URI => you should add http:// otherwise the link in the plugin repositoty will try to fix adding the path of the plugin assuming it's local

the actual hompage show in plugin manager is:
http://plugins.qgis.org/plugins/AequilibraE/www.aequilibrae.com

please fix it

**Comment by pedrocamargo** [comment]
Fixed with commit 2b283acf41fbacebfd108560243ba76b8faec0e7
