### ISSUE TITLE
Saving log and exporting files to CSV are not working

### ISSUE THREAD

**Issue by r-akemii** [AequilibraE/qaequilibrae#227]
When I was working on Issue #222, I noticed that some other QAequilibraE tools are not saving/exporting files as they should.

1. **Project -> logfile -> save to disk** - external window to allow the user to select where he/she wants to save the log is not opening, thus saving is not taking place.
2. **Data -> Display project data -> *Select a matrix* -> Load matrix -> Export** - external window to allow the user to select where he/she wants to save the project matrix opens up, but after typing the desired file name, and pressing *save*, the following error pops up:

![AequilibraE - Um erro ocorreu enquanto executava o código Python_](https://github.com/AequilibraE/qaequilibrae/assets/53949163/cbfd2698-88f4-44cb-9097-82709d8a9cf6)

**Comment by Art-Ev** [comment]
About 1. : logfile is directly stored in the project folder so it's not a big issue (juste a simple text file). Still a bug though...

About 2. : 
working without problem with some .aem demand matrix but I get the same error when trying to export skim matrices (.omx). And these matrices seems very similar... 🤔 

Working demand_matrix (stored in .aem using qAequilibraE import function) : 
![image](https://github.com/AequilibraE/qaequilibrae/assets/83211842/62f19e4b-6c86-4d11-a3a2-0a7ef55baf01)

Non-working skim matrix (created by qAequilibraE during traffic assigment) : 
![image](https://github.com/AequilibraE/qaequilibrae/assets/83211842/e050e31d-8f00-45dd-ab36-c01c7520fd53)

**Comment by r-akemii** [comment]
I talked with Pedro and we'll temporarily disable QAequilibraE's capacity to export CSV files. Some changes need to be done in the AequilibraE code.
