### ISSUE TITLE
qaequilibrae is broken and create infinite QGIS opening loops

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/qaequilibrae#256]
#240 seems to have broken qaequilibrae.

This seems to have led to a problem where, when you try to use a function via qAequilbrae dedicated menus (ex. clicking "Open project") or launching something via qgis processing provider :
- Current QGIS instance/session is freezing 
- a new QGIS instance is launching in a new window, 
- when opened, this new instance opens a new instance which opens a new instance, ...
- New instances have error messages about invalid data sources :
```
2023-11-24T16:55:35     CRITICAL    Invalid Data Source : C:\Users\a.evrard.EGIS\AppData\Roaming\QGIS\QGIS3\profiles\1_Classique\python\plugins\qaequilibrae\packages\cpuinfo\cpuinfo.py is not a valid or recognized data source.
2023-11-24T16:55:35     CRITICAL    Invalid Data Source : D:\OSGeo4W\bin\--json is not a valid or recognized data source.
```

Backed-up version of qaequilibrae (before #240) does not have this issue (using import tr from i18n in each file)

@pedrocamargo or @r-akemii, have you seen something when testing the plugin before merging #240 ?

2 examples of working plugins that use transifex : 
- https://github.com/All4Gis/QGISFMV/tree/master/code
- https://github.com/Arpapiemonte/openoise-map/tree/master

**Comment by Art-Ev** [comment]
Have tried to disable QGIS processing provider and problem is still here

**Comment by r-akemii** [comment]
Hey @Art-Ev ! A couple of months ago, I tested it locally to check if the translations were being placed where they should be and if they were being complied. After merging #240, we merged other pull requests without presenting this error. In fact, yesterday I had this same issue of yours and I've deleted and manually re-added the qaequilibrae and packages folder and it's working fine. I'll take a look at it and make sure to fix whatever is causing this.

Btw, can you give me more details if you're installing qaequilibrae from qgis plug-ins or you're cloning the branch and any other useful information?

**Comment by Art-Ev** [comment]
Hey ! I'm working from #250 (just adding a compiled .qm file before installing the plugin via .zip or copy/cut directly in qgis %appdata% plugin folder). 

Letting the plugin downloading the packages... so maybe it's coming from one of them ?
Have not noticed strange things from packages (only ortools which has a monstrous size, which I don't think was the case before)

Will compare packages versions from the working version used for training and the ones currently installed...

**Comment by Art-Ev** [comment]
Working VS infinite loop package versions (only when different) :
| Package | Training (working) | Current (QGIS loop) |
| :--------  | :-------------------: | :--------------------: |
| AequilibraE | 0.9.3 | 0.9.4 |
| blosc2 | 2.0.0 | 2.3.1 |
| certifi | 2023.11.17 | 2023.7.22 |
| charset | 3.2.0 | 3.3.2 |
| cython | 3.0.2 | 3.0.5 |
| msgpack | 1.0.6 | 1.0.7 |
| msgpack | 1.0.6 | 1.0.7 |
| ndindex | none | 1.7 (new) |
| ortools | 9.7.2996 | 9.8.3296 |
| packaging | 23.1 | 23.2 |
| protobuf | 4.24.3 | 4.25.1 |
| pyaml | none | 23.9.7(new) |
| protobuf | 4.24.3 | 4.25.1 |
| rtree | 1.0.1 | 1.1.0 |
| shapely | 2.0.1 | 2.0.2 |
| shapely | 2.0.1 | 2.0.2 |
| tables | 3.8.0 | 3.9.1 |
| urllib3 | 2.0.5 | 2.1.0 |
| numpy.whl | 1.26.0 | 1.26.2 |
| scipy.whl | 1.11.2 | 1.11.4 |

**Comment by r-akemii** [comment]
Well, according to your error log, it is due to a missing file in cpuinfo package  (...\plugins\qaequilibrae\packages\cpuinfo\cpuinfo.py), which is required by openmatrix. But if you're only copying/pasting files, it shouldn't break at all. Is there the possibility for you to have copied a *packages* folder before this error showed up? Anyway, I'll check it.

**Comment by Art-Ev** [comment]
> Well, according to your error log, it is due to a missing file in cpuinfo package (...\plugins\qaequilibrae\packages\cpuinfo\cpuinfo.py), which is required by openmatrix. But if you're only copying/pasting files, it shouldn't break at all. Is there the possibility for you to have copied a _packages_ folder before this error showed up? Anyway, I'll check it.

cpuinfo.py is not supposed to be a "data source", question is why is qgis trying to use it as a data source ?
Will try to find the time to do a full wipe of my qgis install next week (just in case)

**Comment by r-akemii** [comment]
I think it can be something related to any dependencies we install, but still, I haven't identified what. @pedrocamargo can you help me with this one?

**Comment by r-akemii** [comment]
Hey @Art-Ev I think I found whatever is causing this issue (although I cannot explain why). Apparently, all this is related to the update of Tables from 3.8 to 3.9. I've manually changed the different dependence folders you highlighted above in a new qaequlibrae installation and the only one that effectively worked was downgrading Tables. Probably we can add this to the _requirements.txt_ file.
