### ISSUE TITLE
Delaunay Lines stuck at Assigning Demand

### ISSUE THREAD

**Issue by DoraWu** [AequilibraE/qaequilibrae#47]
I was trying to create Delaunay Lines map using a 49*49 matrix. The Desire Lines feature worked instantly, but Delaunay Lines stuck at Assigning Demand (100%) and not a line on the map. I downloaded AequilibraE Master branch from github on July 7th. Wondering what went wrong?﻿

**Comment by pedrocamargo** [comment]
@DoraWu , without a stack trace or the files you were using it is impossible to guess what went wrong.

**Comment by DoraWu** [comment]
[DesiredLines.zip](https://github.com/AequilibraE/AequilibraE/files/1143717/DesiredLines.zip)
I am attaching the files I am using. Is there a way I can debug?

**Comment by pedrocamargo** [comment]
[image: Inline image 1]
That little cloud symbol in the lower right corner will show you any errors
(if there are any, three little dots will show inside it).

For me it worked like a charm.  Delaunay lines attached.

What version of QGIS are you using?  If using from GitHub, please use the
Version_035 branch. The master might not be stable at times.

Cheers,
Pedro

**Comment by DoraWu** [comment]
I am using QGIS 2.18.10. Honestly I am completely new to QGIS. Thank you for the cloud tip! Here is the error message I got, seems like it could be relating to the python package I have?

2017-07-13T10:45:56	1	An error has occurred while executing Python code:
			
			
			AttributeError: '_DummyThread' object has no attribute '_children'
			
			
			Traceback (most recent call last):
			  File "C:/Users/wuj/.qgis2/python/plugins\AequilibraE\common_tools\worker_thread.py", line 30, in run
			    success = self.doWork()
			  File "C:/Users/wuj/.qgis2/python/plugins\AequilibraE\gis\desire_lines_procedure.py", line 233, in doWork
			    self.report = all_or_nothing(self.matrix, self.graph, self.results)
			  File "C:\Users\wuj\.qgis2\python\plugins\AequilibraE\aequilibrae\paths\assignment.py", line 58, in all_or_nothing
			    pool = ThreadPool(results.cores)
			  File "C:\Python27\Lib\multiprocessing\dummy\__init__.py", line 150, in Pool
			    return ThreadPool(processes, initializer, initargs)
			  File "C:\Python27\Lib\multiprocessing\pool.py", line 685, in __init__
			    Pool.__init__(self, processes, initializer, initargs)
			  File "C:\Python27\Lib\multiprocessing\pool.py", line 136, in __init__
			    self._repopulate_pool()
			  File "C:\Python27\Lib\multiprocessing\pool.py", line 199, in _repopulate_pool
			    w.start()
			  File "C:\Python27\Lib\multiprocessing\dummy\__init__.py", line 73, in start
			    self._parent._children[self] = None
			AttributeError: '_DummyThread' object has no attribute '_children'
			
			
			
			
			Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
			
			
			QGIS version: 2.18.10 Las Palmas, 59e0f78
			
			
			Python Path:
			
			C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processingC:/PROGRA~1/QGIS2~1.18/apps/qgis/./pythonC:/Users/wuj/.qgis2/pythonC:/Users/wuj/.qgis2/python/pluginsC:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/pluginsC:\Python27C:\Python27\ScriptsC:\Python27\LibC:\PROGRA~1\QGIS2~1.18\bin\ C:\Python27\Lib\site-packagesC:\PROGRA~1\QGIS2~1.18\bin\ G:\Dora's Script Resources\PythonC:\PROGRA~1\QGIS2~1.18\bin\python27.zipC:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLsC:\PROGRA~1\QGIS2~1.18\apps\Python27\libC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-winC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tkC:\PROGRA~1\QGIS2~1.18\binC:\PROGRA~1\QGIS2~1.18\apps\Python27C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packagesC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.eggC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.eggC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\libC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PythonwinC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.eggC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicodeC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.eggC:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.eggC:/Users/wuj/.qgis2//pythonC:/Users/Pedro/.qgis2/python/plugins/AequilibraE/C:\Users\wuj\.qgis2\python\plugins\AequilibraEC:\Users\wuj\.qgis2\python\plugins\AequilibraEC:\Users\wuj\.qgis2\python\plugins\AequilibraEC:\Users\wuj\.qgis2\python\plugins\AequilibraE\paths/aequilibrae/

I do not see the delaunay lines attachment....

**Comment by pedrocamargo** [comment]
The error is in the multi-threading (the assignment in AequilibraE is truly
multi-threaded), which is one of the dependencies of the software.

I'll send this error to the QGIS developers group, but for now I'd
recommend you to update your qgis installation after removing the current
one.

Cheers,
Pedro

**Comment by DoraWu** [comment]
Hi Pedro,
Could you share with me what version of QGIS you are using? I have tried both 2.18.10 (the newest release) and version 2.16.3 64-bit but I am still having the same problem...

**Comment by pedrocamargo** [comment]
Hi Dora,
                I was using 2.18.7, but I just tried 2.18.10 64 bits and everything worked fine. I suspect that your problem is in your Python environment, but it is really hard to diagnose.  If you look at the Python path from your stack trace, you can see that components from **C:\Python27** get imported, and depending on your python version, your problem could be residing there, although the Python bug that causes this is really old http://bugs.python.org/issue14881.
If you already have Python version 2.7.5 and newer, then we will need further investigation, and the only solution might be to create something like the patch suggested here:

https://stackoverflow.com/questions/32877365/scikit-random-forest-regressor-attributeerror-thread-object-has-no-attrib.

**Comment by DoraWu** [comment]
Thank you for the response Pedro. Turned out the problem is with line 73 in dummy.__init__.py of the python multiprocessing package. I replaced that line based on the stackoverflow answer and the Delaunay lines works fine now.

**Comment by pedrocamargo** [comment]
Awesome!
