### ISSUE TITLE
Plugin not appearing in QGIS

### ISSUE THREAD

**Issue by sleepiejew** [AequilibraE/qaequilibrae#48]
Not sure what I'm doing wrong

Im running QGIS 2.14.5 LTR, 32-bit, on Windows 10

I search for the plugin and it doesnt show up. Not sure what Im doing wrong

![image](https://user-images.githubusercontent.com/30243509/28286724-2725650c-6b07-11e7-8f1b-404ec1ba06ee.png)

**Comment by pedrocamargo** [comment]
The plugin requires QGIS 2.16 or newer.
