### ISSUE TITLE
Fix the scale of the bandwidths created by the stacked bandwidth.

### ISSUE THREAD

**Issue by harrysmithers** [AequilibraE/qaequilibrae#51]
It would be useful to be able to choose the scale of the bandwidths at the stacked bandwidth interface. 
ie here:

![image](https://user-images.githubusercontent.com/16659692/28504377-6fb0b626-7059-11e7-9a34-710f4aa3eac2.png)

Ideally it would be good to have some ability to choose the value which the max bandwidth is based off, rather than just the max value in the layer. For example a user may want 'layer B' (with a maximum value of less than 100) to have the same scale as 'layer A' (with a maximum value of 100).

**Comment by pedrocamargo** [comment]
Merged to master already. Will be available with the next release
