### ISSUE TITLE
Shortest Path problem:  "from" and "to" field link to wrong data column

### ISSUE THREAD

**Issue by TomasDeLeus** [AequilibraE/qaequilibrae#56]
Hi,

I'm trying to calculate the shortest path on a network.
I configure the tool with the the graph file and link the links_ID to the unique link_id, the Node_ID to the unique Node_id.
The I go to the from field and click on a startpoint. QGIS now fills the value in from field of the first column of my nodes layer (which is ogc_id). Same for To-field.  These values are off course different then my node_id values.
When computing the path, I recieve "No path between 602 and 615", which is normal as these are ogc_id values and not node_id values.
Attached the sqllite database with nodes en links (only to be used for debugging).

QGIS: 2.18.12
AequilibraE: 0.3.5.6

[NetworkDB.zip](https://github.com/AequilibraE/AequilibraE/files/1281055/NetworkDB.zip)

Regards,

Tom

**Comment by pedrocamargo** [comment]
Fixed on version 0.3.5.7
