### ISSUE TITLE
Make bandwidths join style default to round

### ISSUE THREAD

**Issue by harrysmithers** [AequilibraE/qaequilibrae#64]
I would suggest that bandwidths look smoother when the join style is set to round.

@pedrocamargo 

![image](https://user-images.githubusercontent.com/16659692/33304092-f0c66f70-d45a-11e7-893e-87183ee7311f.png)

**Comment by pedrocamargo** [comment]
Can't you set the bandwidths to have round caps after they are generated?

**Comment by pedrocamargo** [comment]
It seems that this was no longer of interest, as the other issue raised by VLC was in conflict with this, and nobody followed up. Closing it then.
