### ISSUE TITLE
Problem with dialog box

### ISSUE THREAD

**Issue by mchibok** [AequilibraE/qaequilibrae#65]
I have a problem with the dialog boxes, where I can hardly click on the button to load matrices. I cannot even click them in the "apply gravity model" section.
<img width="260" alt="capture" src="https://user-images.githubusercontent.com/25492081/33666752-f0efed50-da68-11e7-8c6b-5b803f4dc7b8.PNG">
<img width="132" alt="capture" src="https://user-images.githubusercontent.com/25492081/33667540-1c2d2ada-da6b-11e7-8e8d-cb1ca46f415d.PNG">

**Comment by pedrocamargo** [comment]
Can you let me know the version of QGIS and AequilibraE you are using and the resolution of your screen?

**Comment by mchibok** [comment]
Hey.
QGIS: 2.18.14 64bits (Las Palmas)
AequilibraE: 0.3.5.9
Resolution: 1920 x 1080

**Comment by pedrocamargo** [comment]
Hey there.

I checked on windows machine not used for development and everything seemed normal. Is this windows that you are using? Or something else (My Linux development machine also seemed fine).  I can expand all the boxes to make sure they fit, but just want to make sure that this is not system-specific.

**Comment by mchibok** [comment]
Hello again,
after some troubleshooting, I found out that it was a scaling issue, in the display options. I had it set on 150% which was what Windows recommended. Changed it to 100%, now everything is tiny but it works!
Thanks for your help and the add-on and sorry for the trouble!
