### ISSUE TITLE
Problem with inverse power model - gravity calibration

### ISSUE THREAD

**Issue by mchibok** [AequilibraE/qaequilibrae#66]
Hello,
I seem to have a problem with getting results from the gravity calibration algorithm while using the inverse power model. I never can get a convergence, whether it is really high or low, and whether I set a 1000 iterations or more. Therefore, the "alpha" is always "nan". However, it works perfectly with the negative exponential model. So I did a little bit of troubleshooting and noticed that, in the log results file, the "total of seed matrix" (line 18) for the inverse power is always at 0 while for the negative exp. model it is the same number as the target vectors (i chose the same origin-destination flow & distance columns for both, i've tried it many times).

Also, I don't know Python, but while digging for an answer, I noticed in the gravity_application.py file, line 193 is written 
`self.output[i, :] = np.exp(-beta * cost) * p * a`
while for the power model, at line 195, it's written
`                self.output[i, :] = np.nan_to_num(np.power(cost, -alpha) * p * a)`.

Could this cause the problem?
I'm using Windows 10, QGIS 2.18.15, Aequilibrae 0.3.5.9.
Well, thanks for your help, the Aequilibrae plug-in is really useful, thank you for it.

_inverse power log results on the left, negative exponential on the right, see line 18_
![image](https://user-images.githubusercontent.com/25492081/34620775-ad9ae014-f214-11e7-828f-b8492eaf75d4.png)

**Comment by pedrocamargo** [comment]
Hey @mchibok  Can you upload the dataset you are using?
