### ISSUE TITLE
QGIS 3.0 support

### ISSUE THREAD

**Issue by littlezaide** [AequilibraE/qaequilibrae#77]
This plugin (which looks super exciting) doesn't appear in the QGIS 3.0 plugins list, presumably because it hasn't been migrated yet. Will it be migrated soon, or should people looking to use it stick to QGIS 2.18 for now? 

Thanks!

**Comment by pedrocamargo** [comment]
It will.

I will just have to schedule it. Hopefully in a couple of months...

**Comment by littlezaide** [comment]
Good to know, thanks Pedro.

**Comment by ericstewart22** [comment]
I've started the process of migrating from QGIS 2.18 to 3.0. I'm relatively inexperienced with programming so we'll see how far I get.

**Comment by pedrocamargo** [comment]
Eric, dont you prefer to do this as a concerted effort? There are many parts to migrate, and if we do it in a more organized way it may be easier and avoids you wasting precious hours.

**Comment by ericstewart22** [comment]
Sure - what might I be able to help with? 

My plan was to fix the star imports, run the 2to3 script, and commit the changes to a new branch(?).

Beyond those two things, I'm not sure what else I might be able to help with. I'm using this as an opportunity to learn, so I wouldn't necessary be wasting my time.

**Comment by pedrocamargo** [comment]
Hi Eric.

If that is all you want to do, please start from the gtfs_viewer branch, as that includes some new features.
There will be many other changes needed related to the migration from PyQt4  to PyQt5, but I can do them later.

**Comment by pedrocamargo** [comment]
Work is currently underway
