### ISSUE TITLE
Matrices don't save to files longer than 50 chars

### ISSUE THREAD

**Issue by andreaCola** [AequilibraE/qaequilibrae#78]
And there is no error message pop up

![2018-03-29 16_09_14-qgis 2 18 18 - od_analysis](https://user-images.githubusercontent.com/9732918/38071179-94450598-336b-11e8-8fd3-df43540b1292.png)

**Comment by pedrocamargo** [comment]
Same error encountered by @arobrien 
I will include treatment for this in the version for QGIS 3

**Comment by pedrocamargo** [comment]
Fixed in V 0.5
